version: '3.3'

volumes:
  django-project-localdb-storage:

services:
  project:
    build:
      context: ./toy_project
    command: gunicorn --bind 0.0.0.0:8080 wsgi:application
    env_file:
      - .env_local
    volumes:
      - ./toy_project:/app/
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    volumes:
      - django-project-localdb-storage:/var/lib/postgresql/data/
    env_file: .env_local
    ports:
      - 5432:5432
